# 01 — Data Validation
Validate Reference and Current datasets: shape, schema, missing values, and duplicates.

In [1]:
import sys
sys.path.insert(0, '../src')

import pandas as pd
from validation import (
    load_dataset, get_shape_info, compare_columns,
    compare_dtypes, missing_values_summary,
    duplicate_rows_summary, validate_schema, run_validation
)

## 1. Load Datasets

In [2]:
ref_df = load_dataset('../data/reference.csv')
cur_df = load_dataset('../data/current.csv')
print('Reference:', ref_df.shape)
print('Current  :', cur_df.shape)

Reference: (40, 8)
Current  : (40, 8)

## 2. Dataset Shapes

In [3]:
print(get_shape_info(ref_df, 'Reference'))
print(get_shape_info(cur_df, 'Current'))

{'name': 'Reference', 'rows': 40, 'columns': 8}
{'name': 'Current', 'rows': 40, 'columns': 8}

## 3. Column Comparison

In [4]:
compare_columns(ref_df, cur_df)

{'common_columns': ['age',
  'credit_score',
  'default',
  'education',
  'employment_years',
  'income',
  'loan_amount',
  'loan_purpose'],
 'missing_in_current': [],
 'extra_in_current': [],
 'columns_match': True}

## 4. Data Types Comparison

In [5]:
compare_dtypes(ref_df, cur_df)

             column ref_dtype cur_dtype  dtype_match
0               age     int64     int64         True
1      credit_score     int64     int64         True
2           default     int64     int64         True
3         education    object    object         True
4  employment_years     int64     int64         True
5            income     int64     int64         True
6       loan_amount     int64     int64         True
7      loan_purpose    object    object         True

## 5. Missing Values

In [6]:
ref_miss = missing_values_summary(ref_df, 'Reference')
cur_miss = missing_values_summary(cur_df, 'Current')
print('Reference missing values:')
print(ref_miss if not ref_miss.empty else 'None')
print('\nCurrent missing values:')
print(cur_miss if not cur_miss.empty else 'None')

Reference missing values:
None

Current missing values:
None

## 6. Duplicate Rows

In [7]:
print(duplicate_rows_summary(ref_df, 'Reference'))
print(duplicate_rows_summary(cur_df, 'Current'))

{'dataset': 'Reference', 'total_rows': 40, 'duplicate_rows': 0, 'duplicate_pct': np.float64(0.0)}
{'dataset': 'Current', 'total_rows': 40, 'duplicate_rows': 0, 'duplicate_pct': np.float64(0.0)}

## 7. Full Schema Validation

In [8]:
schema = validate_schema(ref_df, cur_df)
print('Schema valid:', schema['schema_valid'])
schema['dtype_comparison']

Schema valid: True

             column ref_dtype cur_dtype  dtype_match
0               age     int64     int64         True
1      credit_score     int64     int64         True
2           default     int64     int64         True
3         education    object    object         True
4  employment_years     int64     int64         True
5            income     int64     int64         True
6       loan_amount     int64     int64         True
7      loan_purpose    object    object         True

## 8. Full Validation Report

In [9]:
report = run_validation(ref_df, cur_df)
for key, val in report.items():
    print(f'--- {key} ---')
    print(val)
    print()

--- ref_shape ---
{'name': 'Reference', 'rows': 40, 'columns': 8}

--- cur_shape ---
{'name': 'Current', 'rows': 40, 'columns': 8}

--- schema ---
{'schema_valid': True, 'column_comparison': {'common_columns': ['age', 'credit_score', 'default', 'education', 'employment_years', 'income', 'loan_amount', 'loan_purpose'], 'missing_in_current': [], 'extra_in_current': [], 'columns_match': True}, 'dtype_comparison':              column ref_dtype cur_dtype  dtype_match
0               age     int64     int64         True
1      credit_score     int64     int64         True
2           default     int64     int64         True
3         education    object    object         True
4  employment_years     int64     int64         True
5            income     int64     int64         True
6       loan_amount     int64     int64         True
7      loan_purpose    object    object         True, 'dtype_mismatches': Empty DataFrame
Columns: [column, ref_dtype, cur_dtype, dtype_match]
Index: []}

--- ref_missing ---
Empty DataFrame
Columns: [column, missing_count, missing_pct, dataset]
Index: []

--- cur_missing ---
Empty DataFrame
Columns: [column, missing_count, missing_pct, dataset]
Index: []

--- ref_duplicates ---
{'dataset': 'Reference', 'total_rows': 40, 'duplicate_rows': 0, 'duplicate_pct': np.float64(0.0)}

--- cur_duplicates ---
{'dataset': 'Current', 'total_rows': 40, 'duplicate_rows': 0, 'duplicate_pct': np.float64(0.0)}